### ISSUE TITLE
Searching with compound nouns

### ISSUE THREAD

**Issue by MaximilianKresse** [loupe-php/loupe#57]
Hi, I'm a native german speaker and want to use Loupe for a german project. As you may know the german language uses many compound nouns. But as I'm testing this library I discovered that the search does behave a little bit strange in this regards.

Example code:
```php
<?php

use Loupe\Loupe\Configuration;
use Loupe\Loupe\Loupe;
use Loupe\Loupe\LoupeFactory;
use Loupe\Loupe\SearchParameters;

require_once(__DIR__ . '/vendor/autoload.php');

$configuration = Configuration::create()
    ->withPrimaryKey('id')
    ->withSearchableAttributes(['Title'])
    ->withLanguages(['de'])
;

$loupeFactory = new LoupeFactory();
$loupe = $loupeFactory->create(__DIR__ . '/loupe', $configuration);
$loupe->addDocument([
    'id' => 1,
    'Title' => html_entity_decode('Das ist eine Datenbankreplikation'),
]);

$searchParameters = SearchParameters::create()
    ->withQuery('replikation')
    ->withAttributesToSearchOn(['Title'])
    ->withAttributesToHighlight(['Title'])
;
$results = $loupe->search($searchParameters);

var_dump($results->getHits());
```

Expected result:
```
array(1) {...}
```

Actual result:
```
array(0) {
}
```

When searching for something thats not at the start of the word it will not be found. So in this case for "replikation". Is this behavior intended? Is it possible to configure something to support this?

**Comment by Toflar** [comment]
Hey, thanks for giving Loupe a try - I'm German native too 😊 
This is intended, yes. Loupe is a prefix search, like MeiliSearch and probably other engines. So it will never find words that only contain `replikation`. If you need that, Loupe is not the right tool for you. I'm not planning on making this configurable because it would be a tremendous amount of work and require a completely different engine.
It's also documented: https://github.com/loupe-php/loupe/blob/main/docs/configuration.md#minimum-length-for-prefix-search 😊
