### ISSUE TITLE
Support more search operators

### ISSUE THREAD

**Issue by zonky2** [loupe-php/loupe#92]
Support for more search operators like google search - see https://ahrefs.com/blog/google-advanced-search-operators/#tablepress-169

**Comment by Toflar** [comment]
What exactly are you looking for? Just asking but this is very likely completely out of scope for Loupe anyway.

**Comment by zonky2** [comment]
currently the exclusion of words would be interesting... you could of course do this with several searches and subsets

but if that's not Loupe's goal, then so be it...

**Comment by Toflar** [comment]
You mean like `-foobar` in the query? I think that could be doable, yes. But the list you mentioned includes stuff that is definitely never gonna make it :)

**Comment by zonky2** [comment]
> You mean like -foobar in the query?

yes!

**Comment by zonky2** [comment]
One thing has been noticed - apparently all words with OR are searched for in phrases, i.e. in the case of `pilot case` all search results containing either `pilot` or `case` are displayed. In most cases, however, you will want to have all the search results that contain pilot and case. An AND operator would therefore be very helpful.

**Comment by Toflar** [comment]
Operators are not supported and won't be, they are not part of the query but only of the filter. The only thing supported in the query are phrases (`"foo bar"`) and potentially negative queries in the future.
But the problem that `pilot` and `case` are searched individually is indeed wrong, I have filed a bug report: https://github.com/loupe-php/loupe/issues/96

The feature request for negative queries is here: https://github.com/loupe-php/loupe/issues/95
I'm closing this issue because the relevant information has been extracted to separate issues.
